
POST http://localhost/wanda/perl/dbconn.pl/events/new HTTP/1.1
content-type: application/json;charset=UTF-8
        
{
  "headline":      "Unterwegs im Knüllebäck",
  "description":   "Von Knüllebäck(am Hügel) wandern wir innerhalb von 36 Stunden bis Falkenberg/Mark",
  "starttime":     "2017-12-24 18:00:00",
  "startlocation": "vor 'Prügelpeitsch' in Knüllebäck"
}

###
POST http://localhost/wanda/perl/dbconn.pl/members/new HTTP/1.1
content-type: application/json

{
  "username": "Fritz",
  "password": "Manfred",
  "gender": "f",
  "is_admin": "on",
  "motto": "Hol raus, was rauszuholen geht"
}
###

GET http://localhost/wanda/srvrest.pl HTTP/1.1

###

GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET https://example.com/comments?page=2&pageSize=10

###
GET https://httpbin.org/get

###

GET http://localhost/wanda HTTP/1.1

###
POST http://localhost/wanda/test.pl HTTP/1.1
content-type: text/html/json
username: Pepe

{
  "username": "Pepe",
  "password": "pepepass",
  "gender": "m",
  "is_admin": "on",
  "motto": "Pepe for President"
}


###
POST http://localhost/wanda/rest.pl/bookdb/33  HTTP/1.1
Content-Type: application/json

{
  "id":"5557",
  "title" : "Strategy",
  "author" : "J. R. Capablanca"
}

###
GET http://localhost/wanda/rest.pl/bookdb/123  HTTP/1.1
Content-Type: application/json

###
PUT http://localhost/wanda/rest.pl/bookdb/123  HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost/wanda/rest.pl/bookdb/123  HTTP/1.1
Content-Type: application/json
